<?php

namespace JoroBundle\Repository;

/**
 * user1Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class user1Repository extends \Doctrine\ORM\EntityRepository
{
}
